src/main/java/com/qst/entity/User.java
package com.qst.entity;

import java.sql.Timestamp;

public class User extends BaseEntity {

	public static final String PASSWORD = "123456";
	private String login;
	private String name;
	private String passwd;
	private int type;
	private int status; // 0:禁用 1：正常
	private Timestamp lastLogin;

	public User() {

	}

	public User(int id, String login, String name, String passwd, int type,
			int status) {
		this.id = id;
		this.login = login;
		this.name = name;
		this.passwd = passwd;
		this.type = type;
		this.status = status;
	}

	public String getLogin() {
		return login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPasswd() {
		return passwd;
	}

	public void setPasswd(String passwd) {
		this.passwd = passwd;
	}

	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

	public int getStatus() {
		return status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Timestamp getLastLogin() {
		return lastLogin;
	}

	public void setLastLogin(Timestamp lastLogin) {
		this.lastLogin = lastLogin;
	}

	public void setLast_login(Timestamp lastLogin) {
		this.lastLogin = lastLogin;
	}

	static {
		addDesc(User.class, "s0", "禁用", "s1", "正常", "t1", "用户管理员", "t2",
				"题库管理员", "t3", "题库使用者");

	}

	public String getTypeDesc() {
		return getDesc(User.class, "t", type);
	}

	public String getStatusDesc() {
		return getDesc(User.class, "s", status);
	}
}

src/main/java/com/qst/action/AssessmentType/CreateServlet.java
package com.qst.action.AssessmentType;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.WebUtil;

@WebServlet("/assessment/create.action")
public class CreateServlet extends BaseServlet {
	// private IassessmentService assessmentService =
	// ServiceFactory.getService(IassessmentService.class);

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {

		WebUtil.forward(req, resp, "/assessment/create.jsp");
	}
}

src/main/java/com/qst/action/AssessmentType/EditServlet.java
package com.qst.action.AssessmentType;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.RequestUtil;
import com.qst.WebUtil;
import com.qst.entity.AssessmentType;
import com.qst.service.IAssessmentService;
import com.qst.service.ServiceFactory;

@WebServlet("/assessment/edit.action")
public class EditServlet extends BaseServlet {
	private IAssessmentService assessmentService = ServiceFactory.getService(IAssessmentService.class);

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		int id = RequestUtil.getInt(req, "id");
		AssessmentType assessment = assessmentService.findAssessmentById(id);
		req.setAttribute("assessment", assessment);
		WebUtil.forward(req, resp, "/assessment/edit.jsp");
	}
}

src/main/java/com/qst/action/AssessmentType/ListServlet.java
package com.qst.action.AssessmentType;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.WebUtil;
import com.qst.entity.AssessmentType;
import com.qst.service.IAssessmentService;
import com.qst.service.ServiceFactory;

@WebServlet("/assessment/list.action")
public class ListServlet extends BaseServlet {
	private IAssessmentService assessmentService = ServiceFactory
			.getService(IAssessmentService.class);

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		List<AssessmentType> assessmentList = assessmentService.findAllAssessment();
		req.setAttribute("assessmentList", assessmentList);
		WebUtil.forward(req, resp, "/assessment/list.jsp");
	}
}

src/main/java/com/qst/action/PersonalityDimension/EditServlet.java
package com.qst.action.PersonalityDimension;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.RequestUtil;
import com.qst.WebUtil;
import com.qst.entity.PersonalityDimension;
import com.qst.service.IDimensionService;
import com.qst.service.ServiceFactory;

@WebServlet("/dimension/edit.action")
public class EditServlet extends BaseServlet {
	private IDimensionService dimensionService = ServiceFactory.getService(IDimensionService.class);

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		PersonalityDimension kp = dimensionService.findDimensionById(RequestUtil.getInt(req, "id"));
		req.setAttribute("dimension", kp);
		WebUtil.forward(req, resp, "/dimension/edit.jsp");
	}
}

src/main/java/com/qst/action/PersonalityDimension/ListServlet.java
package com.qst.action.PersonalityDimension;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.RequestUtil;
import com.qst.WebUtil;
import com.qst.entity.PersonalityDimension;
import com.qst.entity.AssessmentType;
import com.qst.service.IDimensionService;
import com.qst.service.IAssessmentService;
import com.qst.service.ServiceFactory;

@WebServlet("/dimension/list.action")
public class ListServlet extends BaseServlet {
	private IAssessmentService assessmentService = ServiceFactory
			.getService(IAssessmentService.class);
	private IDimensionService dimensionService = ServiceFactory
			.getService(IDimensionService.class);

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		String submitButton = RequestUtil.getString(req, "create");
		if (submitButton.length() > 0)// 添加操作
		{
			doCreate(req, resp);
		} else {
			doList(req, resp);
		}
	}

	private void doCreate(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		int assessmentId = RequestUtil.getInt(req, "id");
		AssessmentType assessment = assessmentService.findAssessmentById(assessmentId);
		req.setAttribute("assessment", assessment);
		WebUtil.forward(req, resp, "/dimension/create.jsp");
	}

	private void doList(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		req.setAttribute("assessmentList", assessmentService.findAllAssessment());
		// 如果是点击左边导航栏进来，则没有ID，所以就不显示知识点列表
		// 如果是点击查看知识点按钮进来的，就有科目ID，所以就显示该科目下的知识点列表
		int id = RequestUtil.getInt(req, "id");
		// if (id > 0) {
			List<PersonalityDimension> dimensionList = dimensionService
					.findDimensionByAssessment(id);
			req.setAttribute("dimensionList", dimensionList);
		// }
		WebUtil.forward(req, resp, "/dimension/list.jsp");
	}
}

src/main/java/com/qst/action/TestPersonnel/EditServlet.java
package com.qst.action.TestPersonnel;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.RequestUtil;
import com.qst.WebUtil;
import com.qst.entity.TestPersonnel;
import com.qst.service.ITestPersonnelService;
import com.qst.service.ServiceFactory;

@WebServlet("/testPersonnel/edit.action")
public class EditServlet extends BaseServlet {
	private ITestPersonnelService testPersonnelService = ServiceFactory.getService(ITestPersonnelService.class);

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		// 获取学生id
		int id = RequestUtil.getInt(req, "id");
		TestPersonnel testPersonnel = testPersonnelService.findById(id);
		req.setAttribute("testPersonnel", testPersonnel);
		WebUtil.forward(req, resp, "/testPersonnel/edit.jsp");
	}

}

src/main/java/com/qst/action/TestPersonnel/ListServlet.java
package com.qst.action.TestPersonnel;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.RequestUtil;
import com.qst.WebUtil;
import com.qst.entity.Team;
import com.qst.entity.TestPersonnel;
import com.qst.service.ITeamService;
import com.qst.service.ITestPersonnelService;
import com.qst.service.ServiceFactory;

@WebServlet("/testPersonnel/list.action")
public class ListServlet extends BaseServlet {
    private ITeamService classTeamService = ServiceFactory
            .getService(ITeamService.class);
    private ITestPersonnelService testPersonnelService = ServiceFactory
            .getService(ITestPersonnelService.class);

    @Override
    protected void doAction(HttpServletRequest req, HttpServletResponse resp)
            throws ServletException, IOException {
        // 获取班级id
        int tid = RequestUtil.getInt(req, "tid");

        List<TestPersonnel> testPersonnelList = testPersonnelService.findByTeamId(tid);
        req.setAttribute("testPersonnel", testPersonnelList);
        List<Team> teamList = classTeamService.findAll();
        req.setAttribute("teamList", teamList);

        WebUtil.forward(req, resp, "/testPersonnel/list.jsp");
    }

}

src/main/java/com/qst/action/exam/ListServlet.java
package com.qst.action.exam;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.Constant;
import com.qst.WebUtil;
import com.qst.entity.Schedule;
import com.qst.entity.TestPersonnel;
import com.qst.service.IExamService;
import com.qst.service.IScheduleService;
import com.qst.service.IAssessmentService;
import com.qst.service.ServiceFactory;

@WebServlet("/exam/list.action")
public class ListServlet extends BaseServlet {
	private IAssessmentService assessmentService = ServiceFactory.getService(IAssessmentService.class);
	private IExamService examService = ServiceFactory.getService(IExamService.class);
	private IScheduleService scheduleService = ServiceFactory.getService(IScheduleService.class);

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {

		TestPersonnel stu = (TestPersonnel) req.getSession().getAttribute(Constant.CURRENT_TESTPERSONNEL);
		List<Schedule> scheduleList = examService.findScheduleByTestPersonnel(stu);
		req.setAttribute("scheduleList", scheduleList);
		WebUtil.forward(req, resp, "/exam/list.jsp");
	}

}

src/main/java/com/qst/action/question/EditServlet.java
package com.qst.action.question;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.RequestUtil;
import com.qst.WebUtil;
import com.qst.entity.Choice;
import com.qst.entity.Question;
import com.qst.entity.AssessmentType;
import com.qst.service.IQuestionService;
import com.qst.service.IAssessmentService;
import com.qst.service.ServiceFactory;

@WebServlet("/question/edit.action")
public class EditServlet extends BaseServlet {
	private IAssessmentService assessmentService = ServiceFactory.getService(IAssessmentService.class);
	private IQuestionService questionService = ServiceFactory.getService(IQuestionService.class);

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		Question question = questionService.findById(RequestUtil.getInt(req, "id"));
		List<Choice> choices = questionService.findChoices(question.getId());
		AssessmentType assessment = assessmentService.findAssessmentById(question.getAssessmentId());
		req.setAttribute("assessment", assessment);
		req.setAttribute("question", question);
		req.setAttribute("choices", choices);
		WebUtil.forward(req, resp, "/question/edit.jsp");
	}
}

src/main/java/com/qst/action/question/ListServlet.java
package com.qst.action.question;

import java.io.IOException;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.RequestUtil;
import com.qst.WebUtil;
import com.qst.entity.Question;
import com.qst.entity.AssessmentType;
import com.qst.service.IQuestionService;
import com.qst.service.IAssessmentService;
import com.qst.service.ServiceFactory;

@WebServlet("/question/list.action")
public class ListServlet extends BaseServlet {
	private IAssessmentService assessmentService = ServiceFactory
			.getService(IAssessmentService.class);
	private IQuestionService questionService = ServiceFactory
			.getService(IQuestionService.class);

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		String submitButton = RequestUtil.getString(req, "create");
		
		if (submitButton.length() > 0)// 添加操作
		{
			doCreate(req, resp);
		} else {
			doList(req, resp);
		}
	}

	protected void doList(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		List<AssessmentType> assessmentList = assessmentService.findAllAssessment();
		req.setAttribute("assessmentList", assessmentList);

		QuestionQueryParam param = QuestionQueryParam.create(req);
		req.setAttribute("query", param);
		// if (param.getAssessmentId() > 0) {
			List<Question> questionList = questionService.find(param);
			req.setAttribute("questionList", questionList);
		// }
		WebUtil.forward(req, resp, "/question/list.jsp");
	}

	protected void doCreate(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		QuestionQueryParam param = QuestionQueryParam.create(req);
		req.setAttribute("assessment",
				assessmentService.findAssessmentById(param.getAssessmentId()));
		Question question = new Question();
		question.setType(param.getType());
		question.setDifficulty(4);
		req.setAttribute("question", question);
		WebUtil.forward(req, resp, "/question/create.jsp");
	}
}

src/main/java/com/qst/action/schedule/CreateServlet.java
package com.qst.action.schedule;

import java.io.IOException;
import java.sql.Date;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.WebUtil;
import com.qst.entity.Team;
import com.qst.entity.Schedule;
import com.qst.entity.AssessmentType;
import com.qst.entity.User;
import com.qst.service.ITeamService;
import com.qst.service.IAssessmentService;
import com.qst.service.ServiceFactory;

@WebServlet("/schedule/create.action")
public class CreateServlet extends BaseServlet {

	private IAssessmentService assessmentService = ServiceFactory.getService(IAssessmentService.class);
	private ITeamService teamService = ServiceFactory.getService(ITeamService.class);

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		User user = getCurrentUser(req);
		Schedule schedule = (Schedule) req.getAttribute("schedule");
		if (schedule == null) {
			schedule = new Schedule();
			Date today = new Date(System.currentTimeMillis());
			SimpleDateFormat stf=new SimpleDateFormat("yyyy-MM-dd HH:mm");
			schedule.setBeginDate(stf.format(today));
			schedule.setEndDate(stf.format(today));

			req.setAttribute("schedule", schedule);
		}

		List<Team> teamList = teamService.findByCreator(user.getId());
		req.setAttribute("teamList", teamList);
		List<AssessmentType> assessmentList = assessmentService.findAllAssessment();
		req.setAttribute("assessmentList", assessmentList);

		WebUtil.forward(req, resp, "/schedule/create.jsp");
	}

}

src/main/java/com/qst/action/user/CreateServlet.java
package com.qst.action.user;

import java.io.IOException;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.qst.BaseServlet;
import com.qst.WebUtil;
import com.qst.entity.User;

@WebServlet("/user/create.action")
public class CreateServlet extends BaseServlet {

	@Override
	protected void doAction(HttpServletRequest req, HttpServletResponse resp)
			throws ServletException, IOException {
		User user = new User();
		user.setStatus(1);
		user.setType(1);
		req.setAttribute("user", user);
		WebUtil.forward(req, resp, "/user/create.jsp");
	}
}

src/main/webapp/user/create.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <script type="text/javascript" src="${pageContext.request.contextPath }/css/commonCss.js"></script>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/css/table.css"/>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/res/styles.css"/>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/css/input.css"/>
    <title></title>
</head>
<body>
<div style="padding: 10px;">
    <a href="${pageContext.request.contextPath }/user/list.action" class="button">
        <button class="btn btn-warning" style="margin-bottom: 10px">返回列表</button>
    </a>
    <%@ include file="/inc/msg.jsp" %>
    <form action="${pageContext.request.contextPath }/user/save.action" method="post" class="table"
          style="width: 80%;">
        <table class="table table-bordered table-hover table-striped">
            <tr>
                <td class="head">登录名称</td>
                <td><input type="text" name="login"></td>
            </tr>
            <tr>
                <td class="head">真实姓名</td>
                <td><input type="text" name="name"></td>
            </tr>
            <tr>
                <td class="head">用户类型</td>
                <td><input type="radio" name="type" value="1" checked }>用户管理员
                    <input type="radio" name="type" value="2">题库管理员 <input
                            type="radio" name="type" value="3">题库使用者
                </td>
            </tr>
            <tr>
                <td class="head">用户状态</td>
                <td><input type="radio" name="status" value="0">禁用
                    <input type="radio" name="status" value="1" checked>正常
                </td>
            </tr>
            <tr>
                <td colspan="2" class="edit"><input class="btn btn-warning" type="submit" value="保存"/><input
                        class="btn btn-warning" type="reset" value="重置"/></td>
            </tr>
        </table>
    </form>

</div>
</body>
</html>

src/main/webapp/user/edit.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <script type="text/javascript" src="${pageContext.request.contextPath }/css/commonCss.js"></script>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/css/table.css"/>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/res/styles.css"/>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/css/input.css"/>
    <title></title>
</head>
<body>
<div class="from1" style="padding: 10px;">
    <a href="${pageContext.request.contextPath }/user/list.action" class="button">
        <button class="btn btn-warning" style="margin-bottom: 10px">返回列表</button>
    </a>
    <%@ include file="/inc/msg.jsp" %>
    <form action="${pageContext.request.contextPath }/user/update.action" method="post" class="table"
          style="width: 80%;">
        <input type="hidden" name="id" value="${user.id }">
        <table class="table table-bordered table-hover table-striped">
            <tr>
                <td class="head">登录名称</td>
                <td><input type="text" name="login" value="${user.login }"></td>
            </tr>
            <tr>
                <td class="head">真实姓名</td>
                <td><input type="text" name="name" value="${user.name }"></td>
            </tr>
            <tr>
                <td class="head">用户类型</td>
                <td><input type="radio" name="type" value="1"
                ${1 eq user.type?'checked':'' }>用户管理员 <input type="radio"
                                                                  name="type" value="2" ${2 eq user.type?'checked':'' }>题库管理员
                    <input type="radio" name="type" value="3"
                    ${3 eq user.type?'checked':'' }>题库使用者
                </td>
            </tr>
            <tr>
                <td class="head">用户状态</td>
                <td><input type="radio" name="status" value="0"
                ${0 eq user.status?'checked':'' }>禁用 <input type="radio"
                                                              name="status" value="1" ${1 eq user.status?'checked':'' }>正常
                </td>
            </tr>
            <tr>
                <td colspan="2" class="edit"><input type="submit" class="btn btn-warning" value="保存"/><input
                        class="btn btn-warning" type="reset" value="重置"/></td>
            </tr>
        </table>
    </form>

</div>
</body>
</html>

src/main/webapp/user/list.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <script type="text/javascript" src="${pageContext.request.contextPath }/css/commonCss.js"></script>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/css/table.css"/>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/res/styles.css"/>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/css/input.css"/>
</head>
<body>
<div style="padding: 10px;">
    <a href="${pageContext.request.contextPath }/user/create.action">
        <button style="margin-bottom: 10px;" class="btn btn-warning">添加用户</button>
    </a>
    <%@ include file="/inc/msg.jsp" %>
    <table class="table table-bordered table-hover table-striped">
        <tr>
            <th>序号</th>
            <th>登录名</th>
            <th>真实姓名</th>
            <th>类型</th>
            <th>状态</th>
            <th>操作</th>
        </tr>
        <c:forEach var="u" varStatus="vs" items="${userList }">
            <tr>
                <td>${vs.index+1 }</td>
                <td>${u.login }</td>
                <td>${u.name }</td>
                <td>${u.typeDesc }</td>
                <td>${u.statusDesc }</td>
                <td><a class="button" href="${pageContext.request.contextPath }/user/view.action?id=${u.id }">查看</a>
                    <a
                            class="button"
                            href="${pageContext.request.contextPath }/user/edit.action?id=${u.id }">修改</a> <a
                            class="button"
                            href="${pageContext.request.contextPath }/user/view.action?id=${u.id }&delete=1">删除</a> <a
                            class="button"
                            href="${pageContext.request.contextPath }/user/password.action?id=${u.id }">重置密码</a>
                </td>
            </tr>
        </c:forEach>
    </table>
</div>
</body>
</html>

src/main/webapp/user/view.jsp
<%@ page pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
    <script type="text/javascript" src="${pageContext.request.contextPath }/css/commonCss.js"></script>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/css/table.css"/>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/res/styles.css"/>
    <link rel="stylesheet" type="text/css" href="${pageContext.request.contextPath }/css/input.css"/>
</head>
<body>
<div style="padding: 10px;">
    <a href="${pageContext.request.contextPath }/user/list.action" class="button">
        <button class="btn btn-warning" style="margin-bottom: 10px">返回列表</button>
    </a>
    <%@ include file="/inc/msg.jsp" %>
    <table class="table table-bordered table-hover table-striped" style="width: 90%;">
        <tr>
            <td class="head">登录名称</td>
            <td>${user.login }</td>
        </tr>
        <tr>
            <td class="head">真实姓名</td>
            <td>${user.name }</td>
        </tr>
        <tr>
            <td class="head">用户类型</td>
            <td>${user.typeDesc }</td>
        </tr>
        <tr>
            <td class="head">用户状态</td>
            <td>${user.statusDesc }</td>
        </tr>
        <c:if test="${param.delete eq 1 }">
            <tr>
                <td colspan="2" style="text-align: center;"><a
                        href="${pageContext.request.contextPath }/user/delete.action?id=${user.id }"
                        class="button">确认删除</a></td>
            </tr>
        </c:if>
    </table>
</div>
</body>
</html>